
#include <Rcpp.h>

//[[Rcpp::export]]
void fun(int num) {
  // do nothing
}

// [[Rcpp::export]]
int doubleMeAutogenerated(int x) {
  return x+x;
}

// next function _not_ automatically exported or "glued"
SEXP doubleMeOldschool(SEXP xs) {
  try {
    int x = Rcpp::as<int>(xs);
    x += x;
    return Rcpp::wrap(x);
  } catch(...) {
    Rcpp::stop("Something bad happened");
  }
}

// Meh. Now we need to load this by hand :-/
