# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

triple_balance <- function(balance) {
    .Call(`_so62061935_triple_balance`, balance)
}

triple_balance_orig <- function(balance) {
    .Call(`_so62061935_triple_balance_orig`, balance)
}

rcpp_hello_world <- function() {
    .Call(`_so62061935_rcpp_hello_world`)
}

