# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigen_det_cpp <- function(X, n_cores) {
    .Call('_testPkg_eigen_det_cpp', PACKAGE = 'testPkg', X, n_cores)
}

