# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

example_cpp <- function(mat, iters) {
    .Call(`_examplePackage_example_cpp`, mat, iters)
}

rcpp_hello_world <- function() {
    .Call(`_examplePackage_rcpp_hello_world`)
}

