# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BStestby <- function(y1, y2) {
    .Call(`_hdtsdemopkg_BStestby`, y1, y2)
}

CQtest <- function(y1, y2) {
    .Call(`_hdtsdemopkg_CQtest`, y1, y2)
}

