# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_guile <- function(file) {
    .Call(`_RcppGuile_test_guile`, file)
}

rcpp_hello_world <- function() {
    .Call(`_RcppGuile_rcpp_hello_world`)
}

